import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
let authenticated=false,staff=false,allowed=true,found=true;const sent=[];
const stored={id:'00000000-0000-0000-0000-000000000001',customer_email:'saved@example.test',customer_name:'<a href="https://example.test">Name</a>',description:'<b>Cookies</b>',quantity:12,total_amount:54,status:'pending'};
const chain={select(){return this},eq(){return this},async single(){return {data:found?stored:null,error:found?null:{}}}};
globalThis.mailMock=async mail=>{sent.push(mail)};
globalThis.clientMock=()=>({auth:{getUser:async()=>({data:{user:authenticated?{id:'staff'}:null},error:null})},rpc:async name=>({data:name==='is_admin'?staff:allowed,error:null}),from:()=>chain});
globalThis.Deno={env:{get:()=> 'mock'}};
const requestSource=readFileSync('supabase/functions/_shared/request.ts','utf8');
const requestJs=ts.transpileModule(requestSource,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const requestUrl='data:text/javascript;base64,'+Buffer.from(requestJs).toString('base64');
const source=readFileSync('supabase/functions/_shared/order-email.ts','utf8').replace("'./request.ts'",JSON.stringify(requestUrl)).replace(/import .*createClient.*;/,'const createClient=globalThis.clientMock;').replace(/import .*sendMail.*;/,'const sendMail=globalThis.mailMock;');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {orderEmailHandler}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
const call=(body={orderData:{order_id:stored.id,customer_email:'attacker@example.test',customer_name:'Untrusted'}})=>orderEmailHandler('customer')(new Request('https://example.test',{method:'POST',body:JSON.stringify(body)}));
test('anonymous and customer direct mail calls do not send',async()=>{assert.equal((await call()).status,401);authenticated=true;assert.equal((await call()).status,403);assert.equal(sent.length,0);});
test('authorized staff sends only stored recipient and escapes HTML',async()=>{staff=true;assert.equal((await call()).status,200);assert.equal(sent.length,1);assert.equal(sent[0].to,stored.customer_email);assert.ok(sent[0].html.includes('&lt;a href='));assert.ok(!sent[0].html.includes('<b>Cookies'));assert.ok(!sent[0].html.includes('Untrusted'));});
test('missing record and delivery quota cannot send',async()=>{found=false;assert.equal((await call()).status,404);found=true;allowed=false;assert.equal((await call()).status,429);assert.equal(sent.length,1);});
