import { Link } from 'react-router-dom';

export default function Privacy() {
  return <article className="bakery-wrap bakery-policy">
    <header><p className="bakery-kicker">YOUR DETAILS, HANDLED WITH CARE</p><h1>Privacy policy</h1><p className="bakery-policy-date">Last updated: 12 September 2026</p><p>This policy explains how Sugar Mama Cookie Co., a local cookie business serving Albury–Wodonga, handles personal information through our website, customer accounts, bakery workspace and communications.</p></header>
    <aside className="bakery-policy-contact"><strong>A question about your information?</strong><p>Email <a href="mailto:hello@sugarmamacookieco.com.au">hello@sugarmamacookieco.com.au</a> and address your enquiry to the owner, Sugar Mama Cookie Co.</p></aside>
    <section><h2>1. Information we collect</h2><p>When you contact us, request a quote or place an order, we collect the details you provide, such as your name, email, phone number, collection or delivery details, occasion, cookie design, quantities and instructions. We also hold quotes, order history, invoices, messages and inspiration photos you choose to upload.</p><p>For accounts, we hold your email, account identifier, verification status and registration details. Authentication is managed by Supabase. If social sign-in is available and you choose it, the provider shares the account information authorised during sign-in, such as an identifier, email and basic profile details. We do not receive your social provider password.</p><p>Our service providers may collect technical information such as IP address, browser/device details, request times and security logs. For bakery team members who enable notifications, we store a browser push subscription and delivery records.</p></section>
    <section><h2>2. How and why we use it</h2><p>We use your information to prepare quotes, make and manage orders, arrange collection or delivery, provide invoices, answer questions, maintain your account and protect the platform against misuse. Verified accounts can be linked to earlier orders placed using the same email address.</p><p>You can browse without an account and request a quote as a guest. We need sufficient contact and design details to respond and fulfil your request. Account access requires registration and email verification.</p><p>Order and account emails are service communications. We will seek permission where required before sending marketing, and you can ask us to stop marketing at any time without stopping essential order or account messages. We do not sell personal information.</p></section>
    <section><h2>3. Photos, messages and sensitive details</h2><p>Inspiration photos, account conversations and uploaded invoices are private to the bakery and the customer authorised to access the order. Inspiration photos also appear in downloadable quote/order PDFs. Anyone you share a downloaded PDF with can see its contents.</p><p>Only upload material you have permission to share, and avoid unnecessary personal details about other people, particularly children. If you provide allergy or dietary information, we use it to discuss and fulfil your request; please share only what is needed. Contact us if you want to discuss this privately.</p><p>Uploading an inspiration photo does not give us permission to use it in our public gallery or advertising. We will ask before publishing identifiable customer information or private uploads for those purposes.</p></section>
    <section><h2>4. Who helps us provide the service</h2><p>Authorised bakery staff can access information needed for their work. We also use service providers to host and operate the platform:</p><ul><li><strong>Supabase:</strong> accounts, database records, private file storage and server functions.</li><li><strong>Netlify:</strong> website hosting and delivery.</li><li><strong>Zoho Mail:</strong> mailbox services and transactional email.</li><li><strong>Google Fonts:</strong> website fonts; loading them sends technical connection information to Google.</li><li><strong>Apple, Google or Meta:</strong> when you choose an available social sign-in option, follow a social link or contact us through Messenger. Their own privacy policies also apply.</li><li><strong>Browser notification providers:</strong> delivery of notifications when enabled by a bakery team member.</li></ul><p>We may also disclose information where reasonably necessary to comply with law, obtain professional advice, resolve a dispute or protect people and the service. We limit information shared to what is needed for the purpose.</p></section>
    <section><h2>5. Storage and overseas processing</h2><p>Information may be stored or processed in Australia and overseas, including the United States, through our hosting, authentication and other providers. Our Zoho Mail account uses the Australian service. Provider support, infrastructure and subprocessors can involve other countries; this is not a promise that all information stays in Australia.</p><p>You can read more in the <a href="https://supabase.com/privacy">Supabase privacy policy</a>, <a href="https://www.netlify.com/privacy/">Netlify privacy policy</a> and <a href="https://www.zoho.com/privacy.html">Zoho privacy policy</a>, or contact us for information about the services relevant to your enquiry.</p></section>
    <section><h2>6. Browser storage and notifications</h2><p>The platform uses browser storage to maintain sign-in sessions and essential functionality. Our current website does not include advertising pixels or a third-party visitor analytics tracker. Hosting and security logs may still record visits. You can clear browser storage or restrict it in your browser settings, but this may sign you out or affect functionality.</p><p>Bakery Web Push notifications are optional and require browser permission. They may appear on a device’s lock screen. Team members can disable them through the portal or browser/device settings. Links to external social services open services governed by their own privacy settings.</p></section>
    <section><h2>7. Security and retention</h2><p>We use access controls, authenticated accounts and private storage for order attachments to help protect information. No internet service is completely secure. Keep your login details private, sign out on shared devices and tell us if you suspect unauthorised account access.</p><p>We retain information for as long as reasonably needed to manage orders, support customers, maintain appropriate business records and meet legal obligations. When it is no longer needed, we take reasonable steps to delete or de-identify it. Some records may need to be retained for accounting, legal or dispute purposes, and backup copies may remain until their normal retention cycle ends.</p></section>
    <section><h2>8. Access, corrections and deletion</h2><p>Email us to request access to your personal information, correct an error or request account deletion. Include enough detail to identify your account or order, but do not send passwords or full payment card details. We may verify your identity before acting.</p><p>We will explain any information we need to retain or any lawful restriction on a request. Deleting an account does not necessarily delete records we must keep. Payment arrangements are handled with the bakery; please do not put card details in quotes, messages or attachments.</p></section>
    <section><h2>9. Concerns and complaints</h2><p>If you have a privacy concern, email the owner with what happened and the outcome you are seeking. We will investigate and aim to respond within 30 days. If more time is needed, we will let you know.</p><p>If you are not satisfied, you can contact the <a href="https://www.oaic.gov.au/privacy/privacy-complaints">Office of the Australian Information Commissioner</a> for guidance and, where it has jurisdiction, make a complaint. Nothing in this policy limits rights or obligations under applicable Australian law.</p></section>
    <section><h2>10. Changes to this policy</h2><p>We may update this policy as our services or obligations change. The current version and update date will be available on this page. We will provide additional notice of significant changes where appropriate or required.</p></section>
    <Link className="bakery-text-link" to="/">Back to the bakery →</Link>
  </article>;
}
